## Classifying the MNIST digits

#### First load the training and test set

In [1]:
%run read_all_data.py

In [2]:
X_train, y_train = read_all_image_label('train_images.txt', 'train_labels.txt')
X_test, y_test = read_all_image_label('test_images.txt', 'test_labels.txt')

In [3]:
(len(X_train), len(X_test))

(5000, 1000)

#### Convert Python lists to numpy arrays

In [4]:
import numpy as np
y_train_np = np.array(y_train)
y_test_np = np.array(y_test)

In [5]:
img = X_train[0]

In [6]:
from pprint import pprint as pp
pp(img)

['                            ',
 '                            ',
 '                            ',
 '                            ',
 '                            ',
 '                +++++##+    ',
 '        +++++######+###+    ',
 '       +##########+++++     ',
 '        #######+##          ',
 '        +++###  ++          ',
 '           +#+              ',
 '           +#+              ',
 '            +#+             ',
 '            +##++           ',
 '             +###++         ',
 '              ++##++        ',
 '                +##+        ',
 '                 ###+       ',
 '              +++###        ',
 '            ++#####+        ',
 '          ++######+         ',
 '        ++######+           ',
 '       +######+             ',
 '    ++######+               ',
 '    +####++                 ',
 '                            ',
 '                            ',
 '                            ']


In [7]:
# encode a "digit" 

def char2num(c):
    if c==' ':
        n = 0
    elif c=='+':
        n = 1
    elif c=='#':
        n = 2
    else:
        print('This should not happen!')
    return n

In [ ]:
# print(s1)

In [8]:
[ char2num(c) for c in '+ ## ++']

[1, 0, 2, 2, 0, 1, 1]

In [9]:
s1 = ''.join(img)
len(s1)

784

In [11]:
[ char2num(c) for c in s1];

In [25]:
# cheat and put the label in as a feature
def img2array(img, lbl):
    s = ''.join(img)
    arr = [ char2num(c) for c in s]
    arr.append(lbl)
    return np.array(arr)

In [26]:
# cheat and put the label in as a feature
X_train_np = [img2array(img, lbl) for img, lbl in zip(X_train, y_train)]
X_test_np = [img2array(img, lbl) for img, lbl in zip(X_test, y_test)]

In [14]:
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [21]:
model = GaussianNB()
# model = KNeighborsClassifier()

In [27]:
from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.33, random_state=42)

model.fit(X_train_np, y_train_np)
predicted = model.predict(X_test_np)
expected = y_test_np

In [28]:
# Import  metrics
from sklearn import metrics

# summarize the fit of the model

print(metrics.accuracy_score(expected, predicted))
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

0.986
              precision    recall  f1-score   support

           0       1.00      0.99      0.99        90
           1       1.00      0.98      0.99       108
           2       0.97      1.00      0.99       103
           3       0.98      0.99      0.99       100
           4       1.00      0.98      0.99       107
           5       0.98      0.99      0.98        92
           6       0.98      0.99      0.98        91
           7       0.97      0.97      0.97       106
           8       0.98      0.97      0.98       103
           9       1.00      1.00      1.00       100

    accuracy                           0.99      1000
   macro avg       0.99      0.99      0.99      1000
weighted avg       0.99      0.99      0.99      1000

[[ 89   0   1   0   0   0   0   0   0   0]
 [  0 106   2   0   0   0   0   0   0   0]
 [  0   0 103   0   0   0   0   0   0   0]
 [  0   0   0  99   0   1   0   0   0   0]
 [  0   0   0   2 105   0   0   0   0   0]
 [  0   0   0   0   